name: astro-flow
version: 0.1.0
summary: Astro Flow
description: |
  Astro Flow is a focus timer based on the Flowtime method.

confinement: strict
base: core18
grade: devel

# slots:
#   dbus-astro-flow: # adjust accordingly to your app name
#     interface: dbus
#     bus: session
#     name: org.bar.astro_flow # adjust accordingly to your app name and
    
apps:
  astro-flow:
    command: astro_flow
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    # slots:
    #   - dbus-astro-flow
parts:
  astro-flow:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
