name: astro-flow
version: 0.3.0
summary: Astro Flow
description: |
  Astro Flow is a focus timer based on the Flowtime method.

confinement: strict
base: core18
grade: stable
    
apps:
  astro-flow:
    command: astro_flow
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
parts:
  astro-flow:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application

architectures:
  - build-on: amd64
    run-on: [amd64, i386]